vich_uploader:
    db_driver: orm

    mappings:
       plats_images:
            uri_prefix: '%plats_images%'
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
