vich_uploader:
    db_driver: orm

    mappings:
       plat_images:
            uri_prefix: /images/plats
            upload_destination: '%kernel.project_dir%/public/images/plats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
