vich_uploader:
    db_driver: orm

    mappings:
       plat_images:
            uri_prefix: '%app.path.plat_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.plat_images%'
           